<?php

/**
 * Template Name: Search Page Template
 */

get_header();
?>
<div class="wrap">
  <div id="primary" class="content-area">
    <main id="main" class="site-main" role="main">
      <?php if (is_user_logged_in()) : ?>
      <div id="wp-vue-app">
        This text will be replaced by the Vue App when the SPA build (generated by Webpack) is enqueued in WordPress.
      </div><!-- #vue-app -->
      <?php else : ?>
      <div style="width: 100%; text-align: center; height: 100vh; display: flex; flex-direction: column; align-content: center; justify-content: center;">

        <h1 style="font-size: 50px">You need to be logged in to View this.</h1>

        <a href="<?php echo wp_login_url() ?>">Login here</a>
        <span>You will be redirected to this view after login</span>
      </div>
      <?php endif ?>
    </main><!-- #main -->
  </div><!-- #primary -->
</div><!-- .wrap -->

<?php
get_footer();
?>
