<?php

add_action( 'wp_enqueue_scripts', 'vue_dashboard_scripts' );
function vue_dashboard_scripts() {

    // register the Vue build script.
    wp_register_script( // the app build script generated by Webpack.
      'vue_dashboard',
      'http://localhost:8080/index.js',
      array(),
      false,
      true
    );

    wp_register_style('vue_styles', 'http://localhost:8080/main.css');

    wp_enqueue_style('vue_styles');

    wp_enqueue_script( 'vue_dashboard' );
}

add_action ('wp_enqueue_scripts', 'vue_dashboard_scripts' );